[package]
name = "rustywitness"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
tokio = { version = "1", features = [ "macros", "rt-multi-thread", "rt", "fs"] }
url = "2.2.2"
reqwest = "0.11.4"
futures = "0.3.17"

[dependencies.headless_chrome]
version = "0.9.0"
default-features = false

[profile.release]
lto = true
panic = "abort"
