[package]
name = "rustywitness"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = [ "macros", "rt-multi-thread", "rt", "fs", "time", "process"] }
clap = "3.0.0-beta.4"
url = "2.2.2"
once_cell = "1.8.0"
reqwest = "0.11.4"

[profile.release]
lto = true
panic = "abort"
